package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauReport;
import org.linlinjava.litemall.db.domain.SicauReportExample;
import org.linlinjava.litemall.db.domain.SicauReportWithBLOBs;

public interface SicauReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    long countByExample(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int deleteByExample(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int insert(SicauReportWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int insertSelective(SicauReportWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReport selectOneByExample(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReportWithBLOBs selectOneByExampleSelective(@Param("example") SicauReportExample example, @Param("selective") SicauReportWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReportWithBLOBs selectOneByExampleWithBLOBs(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    List<SicauReportWithBLOBs> selectByExampleSelective(@Param("example") SicauReportExample example, @Param("selective") SicauReportWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    List<SicauReportWithBLOBs> selectByExampleWithBLOBs(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    List<SicauReport> selectByExample(SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReportWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauReportWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReportWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    SicauReportWithBLOBs selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauReportWithBLOBs record, @Param("example") SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SicauReportWithBLOBs record, @Param("example") SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauReport record, @Param("example") SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauReportWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SicauReportWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_report
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}