package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauGoodsViolation;
import org.linlinjava.litemall.db.domain.SicauGoodsViolationExample;

public interface SicauGoodsViolationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    long countByExample(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int deleteByExample(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int insert(SicauGoodsViolation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int insertSelective(SicauGoodsViolation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    SicauGoodsViolation selectOneByExample(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    SicauGoodsViolation selectOneByExampleSelective(@Param("example") SicauGoodsViolationExample example, @Param("selective") SicauGoodsViolation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    SicauGoodsViolation selectOneByExampleWithBLOBs(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    List<SicauGoodsViolation> selectByExampleSelective(@Param("example") SicauGoodsViolationExample example, @Param("selective") SicauGoodsViolation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    List<SicauGoodsViolation> selectByExampleWithBLOBs(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    List<SicauGoodsViolation> selectByExample(SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    SicauGoodsViolation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauGoodsViolation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    SicauGoodsViolation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauGoodsViolation record, @Param("example") SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SicauGoodsViolation record, @Param("example") SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauGoodsViolation record, @Param("example") SicauGoodsViolationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauGoodsViolation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SicauGoodsViolation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_goods_violation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauGoodsViolation record);
}