package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauDonationPoint;
import org.linlinjava.litemall.db.domain.SicauDonationPointExample;

public interface SicauDonationPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    long countByExample(SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int deleteByExample(SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int insert(SicauDonationPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int insertSelective(SicauDonationPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    SicauDonationPoint selectOneByExample(SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    SicauDonationPoint selectOneByExampleSelective(@Param("example") SicauDonationPointExample example, @Param("selective") SicauDonationPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    List<SicauDonationPoint> selectByExampleSelective(@Param("example") SicauDonationPointExample example, @Param("selective") SicauDonationPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    List<SicauDonationPoint> selectByExample(SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    SicauDonationPoint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauDonationPoint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    SicauDonationPoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauDonationPoint record, @Param("example") SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauDonationPoint record, @Param("example") SicauDonationPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauDonationPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation_point
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauDonationPoint record);
}