package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauCourierWithdraw;
import org.linlinjava.litemall.db.domain.SicauCourierWithdrawExample;

public interface SicauCourierWithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    long countByExample(SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int deleteByExample(SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int insert(SicauCourierWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int insertSelective(SicauCourierWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    SicauCourierWithdraw selectOneByExample(SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    SicauCourierWithdraw selectOneByExampleSelective(@Param("example") SicauCourierWithdrawExample example, @Param("selective") SicauCourierWithdraw.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    List<SicauCourierWithdraw> selectByExampleSelective(@Param("example") SicauCourierWithdrawExample example, @Param("selective") SicauCourierWithdraw.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    List<SicauCourierWithdraw> selectByExample(SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    SicauCourierWithdraw selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauCourierWithdraw.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    SicauCourierWithdraw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    SicauCourierWithdraw selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauCourierWithdraw record, @Param("example") SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauCourierWithdraw record, @Param("example") SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauCourierWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauCourierWithdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauCourierWithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_withdraw
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}