package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauAuction;
import org.linlinjava.litemall.db.domain.SicauAuctionExample;

public interface SicauAuctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    long countByExample(SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int deleteByExample(SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int insert(SicauAuction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int insertSelective(SicauAuction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    SicauAuction selectOneByExample(SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    SicauAuction selectOneByExampleSelective(@Param("example") SicauAuctionExample example, @Param("selective") SicauAuction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    List<SicauAuction> selectByExampleSelective(@Param("example") SicauAuctionExample example, @Param("selective") SicauAuction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    List<SicauAuction> selectByExample(SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    SicauAuction selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauAuction.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    SicauAuction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    SicauAuction selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauAuction record, @Param("example") SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauAuction record, @Param("example") SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauAuction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauAuction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauAuctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}