package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauAuctionBid;
import org.linlinjava.litemall.db.domain.SicauAuctionBidExample;

public interface SicauAuctionBidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    long countByExample(SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int deleteByExample(SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int insert(SicauAuctionBid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int insertSelective(SicauAuctionBid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    SicauAuctionBid selectOneByExample(SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    SicauAuctionBid selectOneByExampleSelective(@Param("example") SicauAuctionBidExample example, @Param("selective") SicauAuctionBid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    List<SicauAuctionBid> selectByExampleSelective(@Param("example") SicauAuctionBidExample example, @Param("selective") SicauAuctionBid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    List<SicauAuctionBid> selectByExample(SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    SicauAuctionBid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauAuctionBid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    SicauAuctionBid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauAuctionBid record, @Param("example") SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauAuctionBid record, @Param("example") SicauAuctionBidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauAuctionBid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_auction_bid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauAuctionBid record);
}