package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauSensitiveWords;
import org.linlinjava.litemall.db.domain.SicauSensitiveWordsExample;

public interface SicauSensitiveWordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    long countByExample(SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int deleteByExample(SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int insert(SicauSensitiveWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int insertSelective(SicauSensitiveWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    SicauSensitiveWords selectOneByExample(SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    SicauSensitiveWords selectOneByExampleSelective(@Param("example") SicauSensitiveWordsExample example, @Param("selective") SicauSensitiveWords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    List<SicauSensitiveWords> selectByExampleSelective(@Param("example") SicauSensitiveWordsExample example, @Param("selective") SicauSensitiveWords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    List<SicauSensitiveWords> selectByExample(SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    SicauSensitiveWords selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauSensitiveWords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    SicauSensitiveWords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    SicauSensitiveWords selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauSensitiveWords record, @Param("example") SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauSensitiveWords record, @Param("example") SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauSensitiveWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauSensitiveWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauSensitiveWordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_sensitive_words
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}