package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauCommentTags;
import org.linlinjava.litemall.db.domain.SicauCommentTagsExample;

public interface SicauCommentTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    long countByExample(SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int deleteByExample(SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int insert(SicauCommentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int insertSelective(SicauCommentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    SicauCommentTags selectOneByExample(SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    SicauCommentTags selectOneByExampleSelective(@Param("example") SicauCommentTagsExample example, @Param("selective") SicauCommentTags.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    List<SicauCommentTags> selectByExampleSelective(@Param("example") SicauCommentTagsExample example, @Param("selective") SicauCommentTags.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    List<SicauCommentTags> selectByExample(SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    SicauCommentTags selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauCommentTags.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    SicauCommentTags selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    SicauCommentTags selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauCommentTags record, @Param("example") SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauCommentTags record, @Param("example") SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauCommentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauCommentTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauCommentTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_comment_tags
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}