package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauCourierIncome;
import org.linlinjava.litemall.db.domain.SicauCourierIncomeExample;

public interface SicauCourierIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    long countByExample(SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int deleteByExample(SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int insert(SicauCourierIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int insertSelective(SicauCourierIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    SicauCourierIncome selectOneByExample(SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    SicauCourierIncome selectOneByExampleSelective(@Param("example") SicauCourierIncomeExample example, @Param("selective") SicauCourierIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    List<SicauCourierIncome> selectByExampleSelective(@Param("example") SicauCourierIncomeExample example, @Param("selective") SicauCourierIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    List<SicauCourierIncome> selectByExample(SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    SicauCourierIncome selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauCourierIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    SicauCourierIncome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauCourierIncome record, @Param("example") SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauCourierIncome record, @Param("example") SicauCourierIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauCourierIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_courier_income
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauCourierIncome record);
}