package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauDonation;
import org.linlinjava.litemall.db.domain.SicauDonationExample;

public interface SicauDonationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    long countByExample(SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int deleteByExample(SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int insert(SicauDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int insertSelective(SicauDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    SicauDonation selectOneByExample(SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    SicauDonation selectOneByExampleSelective(@Param("example") SicauDonationExample example, @Param("selective") SicauDonation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    List<SicauDonation> selectByExampleSelective(@Param("example") SicauDonationExample example, @Param("selective") SicauDonation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    List<SicauDonation> selectByExample(SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    SicauDonation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauDonation.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    SicauDonation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    SicauDonation selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauDonation record, @Param("example") SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauDonation record, @Param("example") SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauDonation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauDonationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}