package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauCourseMaterial;
import org.linlinjava.litemall.db.domain.SicauCourseMaterialExample;

public interface SicauCourseMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    long countByExample(SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int deleteByExample(SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int insert(SicauCourseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int insertSelective(SicauCourseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    SicauCourseMaterial selectOneByExample(SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    SicauCourseMaterial selectOneByExampleSelective(@Param("example") SicauCourseMaterialExample example, @Param("selective") SicauCourseMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    List<SicauCourseMaterial> selectByExampleSelective(@Param("example") SicauCourseMaterialExample example, @Param("selective") SicauCourseMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    List<SicauCourseMaterial> selectByExample(SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    SicauCourseMaterial selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauCourseMaterial.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    SicauCourseMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    SicauCourseMaterial selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauCourseMaterial record, @Param("example") SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauCourseMaterial record, @Param("example") SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauCourseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauCourseMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SicauCourseMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_course_material
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}