package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SicauOrderRefund;
import org.linlinjava.litemall.db.domain.SicauOrderRefundExample;

public interface SicauOrderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    long countByExample(SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int deleteByExample(SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int insert(SicauOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int insertSelective(SicauOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    SicauOrderRefund selectOneByExample(SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    SicauOrderRefund selectOneByExampleSelective(@Param("example") SicauOrderRefundExample example, @Param("selective") SicauOrderRefund.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    List<SicauOrderRefund> selectByExampleSelective(@Param("example") SicauOrderRefundExample example, @Param("selective") SicauOrderRefund.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    List<SicauOrderRefund> selectByExample(SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    SicauOrderRefund selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SicauOrderRefund.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    SicauOrderRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SicauOrderRefund record, @Param("example") SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SicauOrderRefund record, @Param("example") SicauOrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SicauOrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SicauOrderRefund record);
}