package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class SicauDonation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    public static final Boolean IS_DELETED = Deleted.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    public static final Boolean NOT_DELETED = Deleted.NOT_DELETED.value();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.category
     *
     * @mbg.generated
     */
    private Byte category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.pickup_type
     *
     * @mbg.generated
     */
    private Byte pickupType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.pickup_address
     *
     * @mbg.generated
     */
    private String pickupAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.pickup_time
     *
     * @mbg.generated
     */
    private LocalDateTime pickupTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.reject_reason
     *
     * @mbg.generated
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.auditor_id
     *
     * @mbg.generated
     */
    private Integer auditorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.audit_time
     *
     * @mbg.generated
     */
    private LocalDateTime auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.volunteer_id
     *
     * @mbg.generated
     */
    private Integer volunteerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.finish_time
     *
     * @mbg.generated
     */
    private LocalDateTime finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sicau_donation.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.id
     *
     * @return the value of sicau_donation.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.id
     *
     * @param id the value for sicau_donation.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.user_id
     *
     * @return the value of sicau_donation.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.user_id
     *
     * @param userId the value for sicau_donation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.category
     *
     * @return the value of sicau_donation.category
     *
     * @mbg.generated
     */
    public Byte getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.category
     *
     * @param category the value for sicau_donation.category
     *
     * @mbg.generated
     */
    public void setCategory(Byte category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.quantity
     *
     * @return the value of sicau_donation.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.quantity
     *
     * @param quantity the value for sicau_donation.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.images
     *
     * @return the value of sicau_donation.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.images
     *
     * @param images the value for sicau_donation.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.pickup_type
     *
     * @return the value of sicau_donation.pickup_type
     *
     * @mbg.generated
     */
    public Byte getPickupType() {
        return pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.pickup_type
     *
     * @param pickupType the value for sicau_donation.pickup_type
     *
     * @mbg.generated
     */
    public void setPickupType(Byte pickupType) {
        this.pickupType = pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.pickup_address
     *
     * @return the value of sicau_donation.pickup_address
     *
     * @mbg.generated
     */
    public String getPickupAddress() {
        return pickupAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.pickup_address
     *
     * @param pickupAddress the value for sicau_donation.pickup_address
     *
     * @mbg.generated
     */
    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.pickup_time
     *
     * @return the value of sicau_donation.pickup_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPickupTime() {
        return pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.pickup_time
     *
     * @param pickupTime the value for sicau_donation.pickup_time
     *
     * @mbg.generated
     */
    public void setPickupTime(LocalDateTime pickupTime) {
        this.pickupTime = pickupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.status
     *
     * @return the value of sicau_donation.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.status
     *
     * @param status the value for sicau_donation.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.reject_reason
     *
     * @return the value of sicau_donation.reject_reason
     *
     * @mbg.generated
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.reject_reason
     *
     * @param rejectReason the value for sicau_donation.reject_reason
     *
     * @mbg.generated
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.auditor_id
     *
     * @return the value of sicau_donation.auditor_id
     *
     * @mbg.generated
     */
    public Integer getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.auditor_id
     *
     * @param auditorId the value for sicau_donation.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(Integer auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.audit_time
     *
     * @return the value of sicau_donation.audit_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.audit_time
     *
     * @param auditTime the value for sicau_donation.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(LocalDateTime auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.volunteer_id
     *
     * @return the value of sicau_donation.volunteer_id
     *
     * @mbg.generated
     */
    public Integer getVolunteerId() {
        return volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.volunteer_id
     *
     * @param volunteerId the value for sicau_donation.volunteer_id
     *
     * @mbg.generated
     */
    public void setVolunteerId(Integer volunteerId) {
        this.volunteerId = volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.finish_time
     *
     * @return the value of sicau_donation.finish_time
     *
     * @mbg.generated
     */
    public LocalDateTime getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.finish_time
     *
     * @param finishTime the value for sicau_donation.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(LocalDateTime finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.add_time
     *
     * @return the value of sicau_donation.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.add_time
     *
     * @param addTime the value for sicau_donation.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.update_time
     *
     * @return the value of sicau_donation.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.update_time
     *
     * @param updateTime the value for sicau_donation.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? Deleted.IS_DELETED.value() : Deleted.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sicau_donation.deleted
     *
     * @return the value of sicau_donation.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sicau_donation.deleted
     *
     * @param deleted the value for sicau_donation.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", category=").append(category);
        sb.append(", quantity=").append(quantity);
        sb.append(", images=").append(images);
        sb.append(", pickupType=").append(pickupType);
        sb.append(", pickupAddress=").append(pickupAddress);
        sb.append(", pickupTime=").append(pickupTime);
        sb.append(", status=").append(status);
        sb.append(", rejectReason=").append(rejectReason);
        sb.append(", auditorId=").append(auditorId);
        sb.append(", auditTime=").append(auditTime);
        sb.append(", volunteerId=").append(volunteerId);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SicauDonation other = (SicauDonation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getImages() == null ? other.getImages() == null : this.getImages().equals(other.getImages()))
            && (this.getPickupType() == null ? other.getPickupType() == null : this.getPickupType().equals(other.getPickupType()))
            && (this.getPickupAddress() == null ? other.getPickupAddress() == null : this.getPickupAddress().equals(other.getPickupAddress()))
            && (this.getPickupTime() == null ? other.getPickupTime() == null : this.getPickupTime().equals(other.getPickupTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getRejectReason() == null ? other.getRejectReason() == null : this.getRejectReason().equals(other.getRejectReason()))
            && (this.getAuditorId() == null ? other.getAuditorId() == null : this.getAuditorId().equals(other.getAuditorId()))
            && (this.getAuditTime() == null ? other.getAuditTime() == null : this.getAuditTime().equals(other.getAuditTime()))
            && (this.getVolunteerId() == null ? other.getVolunteerId() == null : this.getVolunteerId().equals(other.getVolunteerId()))
            && (this.getFinishTime() == null ? other.getFinishTime() == null : this.getFinishTime().equals(other.getFinishTime()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getImages() == null) ? 0 : getImages().hashCode());
        result = prime * result + ((getPickupType() == null) ? 0 : getPickupType().hashCode());
        result = prime * result + ((getPickupAddress() == null) ? 0 : getPickupAddress().hashCode());
        result = prime * result + ((getPickupTime() == null) ? 0 : getPickupTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getRejectReason() == null) ? 0 : getRejectReason().hashCode());
        result = prime * result + ((getAuditorId() == null) ? 0 : getAuditorId().hashCode());
        result = prime * result + ((getAuditTime() == null) ? 0 : getAuditTime().hashCode());
        result = prime * result + ((getVolunteerId() == null) ? 0 : getVolunteerId().hashCode());
        result = prime * result + ((getFinishTime() == null) ? 0 : getFinishTime().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    public enum Deleted {
        NOT_DELETED(new Boolean("0"), "未删除"),
        IS_DELETED(new Boolean("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        Deleted(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sicau_donation
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        category("category", "category", "TINYINT", false),
        quantity("quantity", "quantity", "INTEGER", false),
        images("images", "images", "VARCHAR", false),
        pickupType("pickup_type", "pickupType", "TINYINT", false),
        pickupAddress("pickup_address", "pickupAddress", "VARCHAR", false),
        pickupTime("pickup_time", "pickupTime", "TIMESTAMP", false),
        status("status", "status", "TINYINT", true),
        rejectReason("reject_reason", "rejectReason", "VARCHAR", false),
        auditorId("auditor_id", "auditorId", "INTEGER", false),
        auditTime("audit_time", "auditTime", "TIMESTAMP", false),
        volunteerId("volunteer_id", "volunteerId", "INTEGER", false),
        finishTime("finish_time", "finishTime", "TIMESTAMP", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sicau_donation
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}